sudo: false
language: ruby
rvm:
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - rbx-2
  - jruby-9.0.0.0
script: "bundle exec rake test"

gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

matrix:
  allow_failures:
    - rvm: rbx-2
  include:
    - rvm: 2.2.2
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/5.0.gemfile
